### Create ApiKey
POST http://localhost:3001/workspace/ws_01M1XSQD4SFXBW05HQ2GATRT2X/api-key
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDgzMTYsImV4cCI6MTc4ODg0OTIxNiwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.NxCXVGnf2keQkIejXYVLvHaMg-prXRmci5KH0mF4AodViIxNB0NS89oQAVKMpMhYMS4D-2lGGqVC8TBtvQl2okEJGDJHlRXlynAHJ7Qa1y5LDMcS5Jd07s5nrPF-6bVZFlOkAJO9GW5uDEEtEJGrYiY5TzHN2d-siqCC6WyJYhJKBkZ79TPPxzG60LrMDFCZ_DFQL6iZ1krer9CYpG8AUcQUh5hfemJAdo4ZHKlSyoAqV4F3s_ZADTJ63YOzYAzaTPeeM6G7jpf-lYqODDrrMANUpE8hw7h0R3ZmV_uXQHGlOWcAVwX2yMVKBLtYYBwgJ_NM3IOrTKwZxTfoqpvMtQ
Content-Type: application/json

{
  "name": "Example API Key",
  "expireAt": "2025-01-01T00:00:00.000Z"
}


### Update ApiKey
PATCH http://localhost:3001/workspace/ws_01M1XSQD4SFXBW05HQ2GATRT2X/api-key/ak_01M1ZTS19PH9FE9B3MMB5428A4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDgzMTYsImV4cCI6MTc4ODg0OTIxNiwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.NxCXVGnf2keQkIejXYVLvHaMg-prXRmci5KH0mF4AodViIxNB0NS89oQAVKMpMhYMS4D-2lGGqVC8TBtvQl2okEJGDJHlRXlynAHJ7Qa1y5LDMcS5Jd07s5nrPF-6bVZFlOkAJO9GW5uDEEtEJGrYiY5TzHN2d-siqCC6WyJYhJKBkZ79TPPxzG60LrMDFCZ_DFQL6iZ1krer9CYpG8AUcQUh5hfemJAdo4ZHKlSyoAqV4F3s_ZADTJ63YOzYAzaTPeeM6G7jpf-lYqODDrrMANUpE8hw7h0R3ZmV_uXQHGlOWcAVwX2yMVKBLtYYBwgJ_NM3IOrTKwZxTfoqpvMtQ
Content-Type: application/json

{
  "name": "Updated API Key Name",
  "status": "DEACTIVE",
  "expireAt": "2025-12-31T23:59:59.000Z"
}


### Delete ApiKey
DELETE http://localhost:3001/workspace/ws_01M1XSQD4SFXBW05HQ2GATRT2X/api-key/ak_01M1ZTS19PH9FE9B3MMB5428A4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDgzMTYsImV4cCI6MTc4ODg0OTIxNiwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.NxCXVGnf2keQkIejXYVLvHaMg-prXRmci5KH0mF4AodViIxNB0NS89oQAVKMpMhYMS4D-2lGGqVC8TBtvQl2okEJGDJHlRXlynAHJ7Qa1y5LDMcS5Jd07s5nrPF-6bVZFlOkAJO9GW5uDEEtEJGrYiY5TzHN2d-siqCC6WyJYhJKBkZ79TPPxzG60LrMDFCZ_DFQL6iZ1krer9CYpG8AUcQUh5hfemJAdo4ZHKlSyoAqV4F3s_ZADTJ63YOzYAzaTPeeM6G7jpf-lYqODDrrMANUpE8hw7h0R3ZmV_uXQHGlOWcAVwX2yMVKBLtYYBwgJ_NM3IOrTKwZxTfoqpvMtQ
Content-Type: application/json


### Get a single ApiKey
GET http://localhost:3001/workspace/ws_01M1XSQD4SFXBW05HQ2GATRT2X/api-key/ak_01M1ZTS19PH9FE9B3MMB5428A4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDgzMTYsImV4cCI6MTc4ODg0OTIxNiwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.NxCXVGnf2keQkIejXYVLvHaMg-prXRmci5KH0mF4AodViIxNB0NS89oQAVKMpMhYMS4D-2lGGqVC8TBtvQl2okEJGDJHlRXlynAHJ7Qa1y5LDMcS5Jd07s5nrPF-6bVZFlOkAJO9GW5uDEEtEJGrYiY5TzHN2d-siqCC6WyJYhJKBkZ79TPPxzG60LrMDFCZ_DFQL6iZ1krer9CYpG8AUcQUh5hfemJAdo4ZHKlSyoAqV4F3s_ZADTJ63YOzYAzaTPeeM6G7jpf-lYqODDrrMANUpE8hw7h0R3ZmV_uXQHGlOWcAVwX2yMVKBLtYYBwgJ_NM3IOrTKwZxTfoqpvMtQ


### Get all ApiKeys for workspace
GET http://localhost:3001/workspace/ws_01M1XSQD4SFXBW05HQ2GATRT2X/api-key
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDgzMTYsImV4cCI6MTc4ODg0OTIxNiwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.NxCXVGnf2keQkIejXYVLvHaMg-prXRmci5KH0mF4AodViIxNB0NS89oQAVKMpMhYMS4D-2lGGqVC8TBtvQl2okEJGDJHlRXlynAHJ7Qa1y5LDMcS5Jd07s5nrPF-6bVZFlOkAJO9GW5uDEEtEJGrYiY5TzHN2d-siqCC6WyJYhJKBkZ79TPPxzG60LrMDFCZ_DFQL6iZ1krer9CYpG8AUcQUh5hfemJAdo4ZHKlSyoAqV4F3s_ZADTJ63YOzYAzaTPeeM6G7jpf-lYqODDrrMANUpE8hw7h0R3ZmV_uXQHGlOWcAVwX2yMVKBLtYYBwgJ_NM3IOrTKwZxTfoqpvMtQ