### Create ApiKey
POST http://localhost:3001/workspace/ws_01M1XSQD4SFXBW05HQ2GATRT2X/api-key
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODkyMjk1NzMsImV4cCI6MTc4OTIzMDQ3MywiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.iDY3a9Aryarefbgo2IicN6OWDefYVl-IpiVXzPnRFITf_G4hgdrW-CMdN4NFjshv9vx9lj56GAz41tWjog2r5PnMZgv6YwvH6zi2O1kKvmhVK9n-r1YjwI5f6sc8CaRUQZ6Shb2UHjiS-wyhi_VfU04iy_-8sQ_BpuNL1HDHFfuLTm1GkV099Zj_-lIAMOfA6YFPu9ZHJCPqoFyvTBBnU9QKgOL_qBn8O552jccxOMFuSlV8GR5SmVMdUVsOj7RI-8bsrgMTDJFWKnR1g3NivRc8LjuNmccONBzI6Mbh7mCuqgawOTl8k6BTLytmXXCNQPZLJgG7Zgk0egCJZjk-fQ
Content-Type: application/json

{
  "name": "Example ",
  "expireAt": "2025-01-01T00:00:00.000Z"
}


### Update ApiKey
PATCH http://localhost:3001/workspace/ws_01M1XSQD4SFXBW05HQ2GATRT2X/api-key/ak_01M1ZTS19PH9FE9B3MMB5428A4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDgzMTYsImV4cCI6MTc4ODg0OTIxNiwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.NxCXVGnf2keQkIejXYVLvHaMg-prXRmci5KH0mF4AodViIxNB0NS89oQAVKMpMhYMS4D-2lGGqVC8TBtvQl2okEJGDJHlRXlynAHJ7Qa1y5LDMcS5Jd07s5nrPF-6bVZFlOkAJO9GW5uDEEtEJGrYiY5TzHN2d-siqCC6WyJYhJKBkZ79TPPxzG60LrMDFCZ_DFQL6iZ1krer9CYpG8AUcQUh5hfemJAdo4ZHKlSyoAqV4F3s_ZADTJ63YOzYAzaTPeeM6G7jpf-lYqODDrrMANUpE8hw7h0R3ZmV_uXQHGlOWcAVwX2yMVKBLtYYBwgJ_NM3IOrTKwZxTfoqpvMtQ
Content-Type: application/json

{
  "name": "Updated API Key Name",
  "status": "DEACTIVE",
  "expireAt": "2025-12-31T23:59:59.000Z"
}


### Delete ApiKey
DELETE http://localhost:3001/workspace/ws_01M1XSQD4SFXBW05HQ2GATRT2X/api-key/ak_01M1ZTS19PH9FE9B3MMB5428A4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDgzMTYsImV4cCI6MTc4ODg0OTIxNiwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.NxCXVGnf2keQkIejXYVLvHaMg-prXRmci5KH0mF4AodViIxNB0NS89oQAVKMpMhYMS4D-2lGGqVC8TBtvQl2okEJGDJHlRXlynAHJ7Qa1y5LDMcS5Jd07s5nrPF-6bVZFlOkAJO9GW5uDEEtEJGrYiY5TzHN2d-siqCC6WyJYhJKBkZ79TPPxzG60LrMDFCZ_DFQL6iZ1krer9CYpG8AUcQUh5hfemJAdo4ZHKlSyoAqV4F3s_ZADTJ63YOzYAzaTPeeM6G7jpf-lYqODDrrMANUpE8hw7h0R3ZmV_uXQHGlOWcAVwX2yMVKBLtYYBwgJ_NM3IOrTKwZxTfoqpvMtQ
Content-Type: application/json


### Get a single ApiKey
GET http://localhost:3001/workspace/ws_01M1XSQD4SFXBW05HQ2GATRT2X/api-key/ak_01M1ZTS19PH9FE9B3MMB5428A4
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDgzMTYsImV4cCI6MTc4ODg0OTIxNiwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.NxCXVGnf2keQkIejXYVLvHaMg-prXRmci5KH0mF4AodViIxNB0NS89oQAVKMpMhYMS4D-2lGGqVC8TBtvQl2okEJGDJHlRXlynAHJ7Qa1y5LDMcS5Jd07s5nrPF-6bVZFlOkAJO9GW5uDEEtEJGrYiY5TzHN2d-siqCC6WyJYhJKBkZ79TPPxzG60LrMDFCZ_DFQL6iZ1krer9CYpG8AUcQUh5hfemJAdo4ZHKlSyoAqV4F3s_ZADTJ63YOzYAzaTPeeM6G7jpf-lYqODDrrMANUpE8hw7h0R3ZmV_uXQHGlOWcAVwX2yMVKBLtYYBwgJ_NM3IOrTKwZxTfoqpvMtQ


### Get all ApiKeys for workspace
GET http://localhost:3001/workspace/ws_01M1XSQD4SFXBW05HQ2GATRT2X/api-key
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODkyMjk1NzMsImV4cCI6MTc4OTIzMDQ3MywiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.iDY3a9Aryarefbgo2IicN6OWDefYVl-IpiVXzPnRFITf_G4hgdrW-CMdN4NFjshv9vx9lj56GAz41tWjog2r5PnMZgv6YwvH6zi2O1kKvmhVK9n-r1YjwI5f6sc8CaRUQZ6Shb2UHjiS-wyhi_VfU04iy_-8sQ_BpuNL1HDHFfuLTm1GkV099Zj_-lIAMOfA6YFPu9ZHJCPqoFyvTBBnU9QKgOL_qBn8O552jccxOMFuSlV8GR5SmVMdUVsOj7RI-8bsrgMTDJFWKnR1g3NivRc8LjuNmccONBzI6Mbh7mCuqgawOTl8k6BTLytmXXCNQPZLJgG7Zgk0egCJZjk-fQ