### Create Workspace
POST http://localhost:3001/workspace
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDEzMTksImV4cCI6MTc4ODg0MjIxOSwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.KDQPS0e_sCeV2eeFFYf4dX_GD53eKfmY8AWUescW9hJxXQSlXXOdU7v2pYoBCC0PGkfdJHZ_agVYEK2CU-e1z6vJp0A0Vr9AWBOYSagJFkhPpM1gITijj6Ft9tUDCgcbMAfUH8SyGePyuQifIen-oz7LsXWIIdEWDPrAQmBTn7aI1SG8EWTJjIP4v5LCHwf_z-BFYgmhkQbAMCWK-7PxHqhB21FC6UjshGDzF_AVJZtLVGxWyGfEgwBoOYDZJbzq9uPdD8na1Tv7C21UBtQYBUqQsDte4ADYr-p7GEl4WaiAKyUD7f87-8it2iqY_JO8dUfu0VkotF2d8JzilOCwcA

{
  "name": "test-workspace's"
}

### Get All Workspaces (ACTIVE)
GET http://localhost:3001/workspace
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDEzMTksImV4cCI6MTc4ODg0MjIxOSwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.KDQPS0e_sCeV2eeFFYf4dX_GD53eKfmY8AWUescW9hJxXQSlXXOdU7v2pYoBCC0PGkfdJHZ_agVYEK2CU-e1z6vJp0A0Vr9AWBOYSagJFkhPpM1gITijj6Ft9tUDCgcbMAfUH8SyGePyuQifIen-oz7LsXWIIdEWDPrAQmBTn7aI1SG8EWTJjIP4v5LCHwf_z-BFYgmhkQbAMCWK-7PxHqhB21FC6UjshGDzF_AVJZtLVGxWyGfEgwBoOYDZJbzq9uPdD8na1Tv7C21UBtQYBUqQsDte4ADYr-p7GEl4WaiAKyUD7f87-8it2iqY_JO8dUfu0VkotF2d8JzilOCwcA

### Get All Trash Workspaces (DEACTIVE)
GET http://localhost:3001/workspace/trash
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDEzMTksImV4cCI6MTc4ODg0MjIxOSwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.KDQPS0e_sCeV2eeFFYf4dX_GD53eKfmY8AWUescW9hJxXQSlXXOdU7v2pYoBCC0PGkfdJHZ_agVYEK2CU-e1z6vJp0A0Vr9AWBOYSagJFkhPpM1gITijj6Ft9tUDCgcbMAfUH8SyGePyuQifIen-oz7LsXWIIdEWDPrAQmBTn7aI1SG8EWTJjIP4v5LCHwf_z-BFYgmhkQbAMCWK-7PxHqhB21FC6UjshGDzF_AVJZtLVGxWyGfEgwBoOYDZJbzq9uPdD8na1Tv7C21UBtQYBUqQsDte4ADYr-p7GEl4WaiAKyUD7f87-8it2iqY_JO8dUfu0VkotF2d8JzilOCwcA

### Get One Workspace
GET http://localhost:3001/workspace/ws_01M1ZM51T4W6G6YQXQFYBG8AE2
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDEzMTksImV4cCI6MTc4ODg0MjIxOSwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.KDQPS0e_sCeV2eeFFYf4dX_GD53eKfmY8AWUescW9hJxXQSlXXOdU7v2pYoBCC0PGkfdJHZ_agVYEK2CU-e1z6vJp0A0Vr9AWBOYSagJFkhPpM1gITijj6Ft9tUDCgcbMAfUH8SyGePyuQifIen-oz7LsXWIIdEWDPrAQmBTn7aI1SG8EWTJjIP4v5LCHwf_z-BFYgmhkQbAMCWK-7PxHqhB21FC6UjshGDzF_AVJZtLVGxWyGfEgwBoOYDZJbzq9uPdD8na1Tv7C21UBtQYBUqQsDte4ADYr-p7GEl4WaiAKyUD7f87-8it2iqY_JO8dUfu0VkotF2d8JzilOCwcA

### Update Workspace
PATCH http://localhost:3001/workspace/ws_01M1ZM51T4W6G6YQXQFYBG8AE2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDEzMTksImV4cCI6MTc4ODg0MjIxOSwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.KDQPS0e_sCeV2eeFFYf4dX_GD53eKfmY8AWUescW9hJxXQSlXXOdU7v2pYoBCC0PGkfdJHZ_agVYEK2CU-e1z6vJp0A0Vr9AWBOYSagJFkhPpM1gITijj6Ft9tUDCgcbMAfUH8SyGePyuQifIen-oz7LsXWIIdEWDPrAQmBTn7aI1SG8EWTJjIP4v5LCHwf_z-BFYgmhkQbAMCWK-7PxHqhB21FC6UjshGDzF_AVJZtLVGxWyGfEgwBoOYDZJbzq9uPdD8na1Tv7C21UBtQYBUqQsDte4ADYr-p7GEl4WaiAKyUD7f87-8it2iqY_JO8dUfu0VkotF2d8JzilOCwcA

{
  "name": "update-workspace",
  "status": "DEACTIVE"
}

### Delete Workspace
DELETE http://localhost:3001/workspace/ws_01M1ZM51T4W6G6YQXQFYBG8AE2
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzAxS1M2Wk1CU0ZTMko1UTFHWkFTNjRLUDVEIiwiZW1haWwiOiJtdWxhbmlhc2hpdEBnbWFpbC5jb20iLCJwaG9uZSI6Iis5MTkzMTMxOTQxMTAiLCJpYXQiOjE3ODg4NDEzMTksImV4cCI6MTc4ODg0MjIxOSwiaXNzIjoiYXV0aC5mbHVvY2UuY29tIn0.KDQPS0e_sCeV2eeFFYf4dX_GD53eKfmY8AWUescW9hJxXQSlXXOdU7v2pYoBCC0PGkfdJHZ_agVYEK2CU-e1z6vJp0A0Vr9AWBOYSagJFkhPpM1gITijj6Ft9tUDCgcbMAfUH8SyGePyuQifIen-oz7LsXWIIdEWDPrAQmBTn7aI1SG8EWTJjIP4v5LCHwf_z-BFYgmhkQbAMCWK-7PxHqhB21FC6UjshGDzF_AVJZtLVGxWyGfEgwBoOYDZJbzq9uPdD8na1Tv7C21UBtQYBUqQsDte4ADYr-p7GEl4WaiAKyUD7f87-8it2iqY_JO8dUfu0VkotF2d8JzilOCwcA
